<?php

return [
    ['code' => '00', 'description' => 'Sin selección'],
    ['code' => '01', 'description' => 'Aguascalientes'],
    ['code' => '02', 'description' => 'Baja California'],
    ['code' => '03', 'description' => 'Baja California Sur'],
    ['code' => '04', 'description' => 'Campeche'],
    ['code' => '05', 'description' => 'Coahuila'],
    ['code' => '06', 'description' => 'Colima'],
    ['code' => '07', 'description' => 'Chiapas'],
    ['code' => '08', 'description' => 'Chihuahua'],
    ['code' => '09', 'description' => 'Distrito Federal'],
    ['code' => '10', 'description' => 'Durango'],
    ['code' => '11', 'description' => 'Guanajuato'],
    ['code' => '12', 'description' => 'Guerrero'],
    ['code' => '13', 'description' => 'Hidalgo'],
    ['code' => '14', 'description' => 'Jalisco'],
    ['code' => '15', 'description' => 'Estado de México'],
    ['code' => '16', 'description' => 'Michoacán'],
    ['code' => '17', 'description' => 'Morelos'],
    ['code' => '18', 'description' => 'Nayarit'],
    ['code' => '19', 'description' => 'Nuevo León'],
    ['code' => '20', 'description' => 'Oaxaca'],
    ['code' => '21', 'description' => 'Puebla'],
    ['code' => '22', 'description' => 'Querétaro'],
    ['code' => '23', 'description' => 'Quintana Roo'],
    ['code' => '24', 'description' => 'San Luis Potosí'],
    ['code' => '25', 'description' => 'Sinaloa'],
    ['code' => '26', 'description' => 'Sonora'],
    ['code' => '27', 'description' => 'Tabasco'],
    ['code' => '28', 'description' => 'Tamaulipas'],
    ['code' => '29', 'description' => 'Tlaxcala'],
    ['code' => '30', 'description' => 'Veracruz'],
    ['code' => '31', 'description' => 'Yucatán'],
    ['code' => '32', 'description' => 'Zacatecas'],
    ['code' => '33', 'description' => 'Extranjeros'],
];