<?php

return [

    'combustibles_fosiles' => [
        ['code' => '002', 'description' => 'Butano'],
        ['code' => '009', 'description' => 'Carbón mineral'],
        ['code' => '006', 'description' => 'Combustóleo'],
        ['code' => '008', 'description' => 'Coque de carbón'],
        ['code' => '007', 'description' => 'Coque de petróleo'],
        ['code' => '005', 'description' => 'Diésel'],
        ['code' => '003', 'description' => 'Gasolinas y gasavión'],
        ['code' => '010', 'description' => 'Otros combustibles fósiles'],
        ['code' => '001', 'description' => 'Propano'],
        ['code' => '000', 'description' => 'Sin selección'],
        ['code' => '004', 'description' => 'Turbosina y otros kerosenos'],
    ],

    'plaguicidas' => [
        ['code' => '002', 'description' => 'Categoría 3'],
        ['code' => '003', 'description' => 'Categoría 4'],
        ['code' => '001', 'description' => 'Categorías 1 y 2'],
        ['code' => '000', 'description' => 'Sin selección'],
    ],

    'alimentos_alta_densidad_calorica' => [
        ['code' => '008', 'description' => 'Alimentos preparados a base de cereales'],
        ['code' => '001', 'description' => 'Botanas'],
        ['code' => '003', 'description' => 'Chocolate y demás productos derivados del cacao'],
        ['code' => '006', 'description' => 'Cremas de cacahuate y avellanas'],
        ['code' => '005', 'description' => 'Dulces de frutas y hortalizas'],
        ['code' => '007', 'description' => 'Dulces de leche'],
        ['code' => '004', 'description' => 'Flanes y pudines'],
        ['code' => '009', 'description' => 'Helados, nieves y paletas de hielo'],
        ['code' => '002', 'description' => 'Productos de confitería'],
        ['code' => '000', 'description' => 'Sin selección'],
    ],

    'combustibles_automotrices' => [
        ['code' => '004', 'description' => 'Combustibles no fósiles'],
        ['code' => '003', 'description' => 'Diésel'],
        ['code' => '002', 'description' => 'Gasolina mayor o igual a 91 octanos'],
        ['code' => '001', 'description' => 'Gasolina menor a 91 octanos'],
        ['code' => '000', 'description' => 'Sin selección'],
    ],

    'bebidas_alcoholicas' => [
        ['code' => '001', 'description' => 'Aguardiente Abocado o Reposado'],
        ['code' => '005', 'description' => 'Aguardiente añejo'],
        ['code' => '008', 'description' => 'Aguardiente con Sabor'],
        ['code' => '002', 'description' => 'Aguardiente Standard (blanco u oro)'],
        ['code' => '023', 'description' => 'Amaretto'],
        ['code' => '017', 'description' => 'Anís'],
        ['code' => '012', 'description' => 'Bacanora'],
        ['code' => '045', 'description' => 'Bebidas Refrescantes'],
        ['code' => '022', 'description' => 'Brandy'],
        ['code' => '028', 'description' => 'Brandy Reserva'],
        ['code' => '033', 'description' => 'Brandy Solera'],
        ['code' => '037', 'description' => 'Calvados'],
        ['code' => '044', 'description' => 'Cerveza'],
        ['code' => '003', 'description' => 'Charanda'],
        ['code' => '009', 'description' => 'Cocteles'],
        ['code' => '039', 'description' => 'Cognac V.S.'],
        ['code' => '042', 'description' => 'Cognac V.S.O.P'],
        ['code' => '043', 'description' => 'Cognac X.O.'],
        ['code' => '013', 'description' => 'Comiteco'],
        ['code' => '034', 'description' => 'Cremas base Whisky'],
        ['code' => '018', 'description' => 'Habanero'],
        ['code' => '014', 'description' => 'Lechuguilla o raicilla'],
        ['code' => '024', 'description' => 'Licor de Café o Cacao'],
        ['code' => '004', 'description' => 'Licor de hierbas regionales'],
        ['code' => '010', 'description' => 'Licores y Cremas hasta 20% Alc. Vol.'],
        ['code' => '025', 'description' => 'Licores y Cremas más de 20% Al. Vol.'],
        ['code' => '015', 'description' => 'Mezcal'],
        ['code' => '047', 'description' => 'Otros'],
        ['code' => '011', 'description' => 'Parras'],
        ['code' => '007', 'description' => 'Rompope'],
        ['code' => '020', 'description' => 'Ron'],
        ['code' => '027', 'description' => 'Ron Añejo'],
        ['code' => '029', 'description' => 'Ron con Sabor'],
        ['code' => '030', 'description' => 'Ron Reserva'],
        ['code' => '000', 'description' => 'Sin selección'],
        ['code' => '016', 'description' => 'Sotol'],
        ['code' => '041', 'description' => 'Tenessee de Luxe'],
        ['code' => '036', 'description' => 'Tenessee Standard'],
        ['code' => '038', 'description' => 'Tequila añejo 100% agave'],
        ['code' => '021', 'description' => 'Tequila joven o blanco'],
        ['code' => '031', 'description' => 'Tequila joven o blanco 100% agave'],
        ['code' => '032', 'description' => 'Tequila reposado 100% agave'],
        ['code' => '026', 'description' => 'Tequila reposado o añejo'],
        ['code' => '046', 'description' => 'Vinos de mesa'],
        ['code' => '019', 'description' => 'Vodka'],
        ['code' => '035', 'description' => 'Whisky o Whiskey, Borbon o Bourbon'],
        ['code' => '040', 'description' => 'Whisky o Whiskey, Borbon o Bourbon'],
    ],

];